cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove



app_name = 'cart'
urlpatterns = [
    path('', cart_detail, name='cart-detail'),
    path('add/<int:product_id>/', cart_add, name='cart-add'),
    path('remove/<int:product_id>/', cart_remove, name='cart-remove')

]

orders/urls.py
from django.urls import path
from .views import create_order, OrdersListView, OrderDetailView, order_success

app_name = 'orders'
urlpatterns = [
    path('', OrdersListView.as_view(), name='order-list'),
    path('new_order/', create_order, name='order-create'),
    path('order-info/<str:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('order_success/', order_success, name='order-success'),

]

products/urls.py
from django.urls import path
from .views import index, CategoryCreateView, CategoryListView, SubCategoryCreateView, ProductCreateView, ProductListView, ProductDetailView


app_name = 'products'
urlpatterns = [
    path('', index, name='index'),
    
    path('category-form/', CategoryCreateView.as_view(), name='category-form'),
    path('category-list/', CategoryListView.as_view(), name='category-list'),
    
    path('subcategory-form/', SubCategoryCreateView.as_view(), name='subcategory-form'),
        
    path('product-form/', ProductCreateView.as_view(), name='product-form'),
    path('product-list/<slug:cat_slug>/<slug:subcat_slug>/', ProductListView.as_view(), name='product-list'),
    path('product-detail/<slug:cat_slug>/<slug:subcat_slug>/<slug:prod_slug>/', ProductDetailView.as_view(), name='product-detail'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from products import urls as urls_products
from users import urls as urls_users
from cart import urls as urls_cart
from orders import urls as urls_orders
from django.conf.urls.static import static
from shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(urls_users)),
    path('cart/', include(urls_cart)),
    path('orders/', include(urls_orders)),
	path('', include(urls_products)),
]

if settings.DEBUG: 
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.contrib.auth.models import User

from django.db import models
from cart.models import Products
from django.utils.timezone import datetime
 
STATUS_CHOICES = (
    ("in_process", "В обработке"),
    ("confirmed", "Подтвержден"),
    ("waiting_payment", "Ожидает оплаты"),
    ("paid", "Оплачен"),
    ("assembly", "Собирается"),
    ("on_way", "В пути"),
    ("delivery_point", "В пунке выдачи"),
    ("delivered", "Доставлен"),
    ("canceled", "Отменен"),
)
 
def get_order_number():
    date = datetime.now().strftime('%Y-%m-%d')
    if Order.objects.all().last():
        last_order = Order.objects.all().last()
        if last_order.number[0:10] == date:
            num = int(last_order.number[11::]) + 1
        else:
            num = 1
    else:
        return f'{date}-1'
    return f'{date}-{num}'
 
 
class Order(models.Model):
    number = models.CharField(primary_key=True, unique=True, max_length=256, default=get_order_number, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, editable=False)
    first_name = models.CharField(max_length=256, verbose_name='Имя')
    last_name = models.CharField(max_length=256, verbose_name='Фамилия')
    email = models.EmailField(verbose_name='Электронная почта')
    phone = models.CharField(max_length=12, verbose_name='Телефон')
    address = models.TextField(verbose_name="Адрес")
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default='in_process')
    payment = models.CharField(max_length=50, verbose_name='Способ оплаты')
    deliviry = models.CharField(max_length=50, verbose_name='Способ доставки')
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Сумма заказа', default=0)
 
 
    def __str__(self):
        return " ".join(["order_",self.number])
 
 
class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order_items')
    product = models.ForeignKey(Products, on_delete=models.CASCADE, related_name='orders')
    quantity = models.IntegerField()

orders/forms.py
from django import forms
from .models import Order

PAYMENT_CHOICES = (
    ("cash", "Наличными"),
    ("card_online", "Картой онлайн"),
    ("card_courier", "Картой курьеру"),
)

DELIVERY_CHOICES = (
    ("pick_up_point", "Пункт выдачи"),
    ("delivery", "Курьерская доставка"),
    ("mail", "Почта России"),
    ("cdek", "СДЭК"),
)

class OrderForm(forms.ModelForm):
    payment  = forms.ChoiceField(choices=PAYMENT_CHOICES, label='Способ оплаты')
    deliviry = forms.ChoiceField(choices=DELIVERY_CHOICES, label='Способ Доставки')
    
    class Meta:
        model = Order
        exclude = ['number', 'status', 'total_price']

orders/views.py
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.generic import ListView, DetailView

from cart.models import CartUser
from cart.views import Cart, ProductCartUser
from products.models import Products

from .forms import OrderForm
from .models import Order, OrderItem


def cart_delete(request, cart):
    cart.clear()
    cart_user = CartUser.objects.get(user=request.user)
    cart_user.delete()
    

# создание заказа
def create_order(request):
    # выдаем пустую форму для заполнения информации о заказе
    if request.method == 'GET':
        form = OrderForm()
        context = {'form': form}
        
        return render(request, template_name="orders/order.html", context=context)
    
    # получаем корзину из БД
    if request.user.id:
        cart = ProductCartUser(request).cart
    # либо получаем корзину из сессии
    else:
        cart = Cart(request).cart

    if len(cart) == 0:
        url = reverse('products:index')
        return redirect(url)
        
    # если нажата кнопка подтвердить заказ
    # получаем заполненную форму
    
    order_form = OrderForm(request.POST)
    
    # сохраняем пустой заказ в БД
    if order_form.is_valid():
        order_form.save()

        
        
        # получаем номер только что созданного пустого заказа
        order_num = order_form.instance.number
        if request.user.id:
            user = User.objects.get(pk=request.user.id)
            order = Order.objects.get(number = order_num)
            order.user = user
        else:
            # получаем объект самого заказа из БД
            order = Order.objects.get(number = order_num)
        
        total_price = 0
        
        # проходимся по корзине и заносим товары в заказ
        for product_id in cart.keys():
            product = Products.objects.get(pk=product_id)
            quantity = cart[product_id]['quantity']
            total_price += product.price * int(quantity)
            # создаем позицию товара в заказе
            OrderItem.objects.create(order=order, product=product, quantity=quantity)
        
        order.total_price = total_price
        order.save()
        
        if request.user.id:
            cart_delete(request, cart)
        else:
            cart.clear()
        
        context = {'order': order}
              
        return render(request, 'orders/order_success.html', context=context)
            

class OrdersListView(ListView):
    model = Order
    template_name = 'orders/user_orders.html'
    context_object_name = 'orders'
    
    def get_queryset(self):
        super().get_queryset()
        user = self.request.user
        query = Q(email = user.email) | Q(user=user)
        queryset = Order.objects.filter(query)
        
        return queryset
        

class OrderDetailView(DetailView):
    model = Order
    template_name = 'orders/order-detail.html'
    context_object_name = 'order'


    
def order_success():
    pass
    

orders/templates/orders/order-detail.html
{% extends "products/base.html" %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/orders.css'%}" type="text/css">

    <table class="order-info">
        <tr>    
            <th>Товар</th>
            <th>Цена</th>
            <th>Количество</th>
            <th>Стоимость</th>
        </tr>
        {% for item in order.order_items.all %}
                <tr>
                    <td><a href="{{item.product.get_absolute_url}}">{{item.product.name}}</a></td>
                    <td>{{item.product.price}}</td>
                    <td>{{item.quantity}}</td>
                    <td>{{item.get_total_price}}</td>
                </tr>
        {% endfor %}

        
{% endblock content %}

orders/templates/orders/order.html
{% extends "products/base.html" %}
{% load static %}
{% load thumbnail %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/orders.css'%}" type="text/css">
<div style="display: flex">
<div style="display: inline-block; margin-left: 200px">

    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit">Оформить заказ</button>
</form>
</div>

<table class='order-create'>
        <tr>
            <th>Товар</th>
            <th>Количество</th>
            <th>Цена за ед.</th>
            <th>Стоимость</th>
        </tr>
        {% for item in cart %}
            {% with product=item.product %}
            <tr>
                <td>{{ product.name }}</td>
                <td>
                {{item.quantity}}
                </td>
                <td class="num">{{ item.price }} руб.</td>
                <td class="num">{{ item.total_price }} руб.</td>
            </tr>
            {% endwith %}
        {% endfor %}

        <tr class="Стоимость">
            <td>Сумма заказа:</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
    
</table>

</div>

{% endblock content %}

orders/templates/orders/order_success.html
{% extends "products/base.html" %}

{% block content %}
<h1>Ваш заказ успешно оформлен!</h1>
<h2>Номер Вашего заказа <span style="color: red">{{order.number}}</span> от {{order.created_at|date:"d.m.Y"}}</h2>
<h3> <a href={% url "products:index" %}> Вернуться к покупкам </a></h3>

{% endblock content %}

orders/templates/orders/user_orders.html
{% extends "products/base.html" %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/orders.css'%}" type="text/css">

    <table class="order-info">
        <tr>    
            <th>Номер заказа</th>
            <th>Статус</th>
            <th>Сумма заказа</th>
            <th>Способ оплаты</th>
            <th>Вариант доставки</th>
        </tr>
        {% for  order in orders  %}
                <tr>
                    <td>
                       <a href={% url "orders:order-detail" order.number%}>{{order.number}}</a>
                    </td>
                    <td>{{order.number}}</td>
                    <td>{{order.status}}</td>
                    <td>{{order.total_price}}</td>
                    <td>{{order.payment}}</td>
                    <td>{{order.deliviry}}</td>
                </tr>
        {% endfor %}
        
{% endblock content %}