cart/urls.py
from django.urls import path
from .views import cart_add, cart_detail, cart_remove



app_name = 'cart'
urlpatterns = [
    path('', cart_detail, name='cart-detail'),
    path('add/<int:product_id>/', cart_add, name='cart-add'),
    path('remove/<int:product_id>/', cart_remove, name='cart-remove')

]

orders/urls.py
from django.urls import path
from .views import create_order, OrdersListView, OrderDetailView, order_success

app_name = 'orders'
urlpatterns = [
    path('', OrdersListView.as_view(), name='order-list'),
    path('new_order/', create_order, name='order-create'),
    path('order-info/<str:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('order_success/', order_success, name='order-success'),

]

products/urls.py
from django.urls import path
from .views import index, CategoryCreateView, CategoryListView, SubCategoryCreateView, ProductCreateView, ProductListView, ProductDetailView


app_name = 'products'
urlpatterns = [
    path('', index, name='index'),
    
    path('category-form/', CategoryCreateView.as_view(), name='category-form'),
    path('category-list/', CategoryListView.as_view(), name='category-list'),
    
    path('subcategory-form/', SubCategoryCreateView.as_view(), name='subcategory-form'),
        
    path('product-form/', ProductCreateView.as_view(), name='product-form'),
    path('product-list/<slug:cat_slug>/<slug:subcat_slug>/', ProductListView.as_view(), name='product-list'),
    path('product-detail/<slug:cat_slug>/<slug:subcat_slug>/<slug:prod_slug>/', ProductDetailView.as_view(), name='product-detail'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from products import urls as urls_products
from users import urls as urls_users
from cart import urls as urls_cart
from orders import urls as urls_orders
from django.conf.urls.static import static
from shop import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(urls_users)),
    path('cart/', include(urls_cart)),
    path('orders/', include(urls_orders)),
	path('', include(urls_products)),
]

if settings.DEBUG: 
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from .views import register, log_in, log_out, UserDetailView

app_name = 'users'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('user-info/<int:pk>/', UserDetailView.as_view(), name='user-info'),
]

products/models.py
from django.db import models
from django.urls import reverse
# from django.utils.text import slugify
from slugify import slugify

def create_directory_path(instance, filename):
    return f'images/{instance.category.slug}/{instance.subcategory.slug}'

class Category(models.Model):
    name = models.CharField(max_length=50, verbose_name='Имя категории', unique=True)
    description = models.TextField(max_length=1000, verbose_name='Описание категории')
    slug = models.SlugField(max_length=256, unique=True, verbose_name='URL-имя', editable=False)  # отображает имя сущности

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name',]

    def __str__(self) -> str:
        return self.name

        
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)



class SubCategory(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name='Имя подкатегории')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория', related_name='categories')
    slug = models.SlugField(max_length=70, unique=True, verbose_name='URL-имя', editable=False)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(SubCategory, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.name
    
    def get_absolute_url(self):  # Используется для получения URL возвращает страничку
        return reverse('products:product-list', kwargs={'cat_slug': self.category.slug, 'subcat_slug':self.slug})  
    

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'
        ordering = ['name',]



class Products(models.Model):
    name = models.CharField(max_length=128, unique=True, verbose_name='Название товара')
    description = models.TextField(max_length=1000, verbose_name='Описание товара')
    price = models.FloatField(verbose_name='Цена товара')
    slug = models.SlugField(max_length=148, unique=True, verbose_name='URL-имя', editable=False)
    is_available = models.BooleanField(default=True, verbose_name='Доступность товара')
    created_at = models.DateField(auto_now_add=True, verbose_name='Дата добавления товара')
    subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, verbose_name='Подкатегория', editable=False, related_name='subcategory')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория', editable=False, related_name='category')
    image = models.ImageField(upload_to=create_directory_path, verbose_name='Изображение товара', null=True, blank=True)
    
    class Meta:
       verbose_name = 'Товар'
       verbose_name_plural = 'Товары'
       ordering = ['name', '-price']

    
    def get_absolute_url(self):  # Используется для получения URL возвращает страничку
        return reverse('products:product-detail', kwargs={
            'cat_slug': self.category.slug, 
            'subcat_slug':self.subcategory.slug, 
            'prod_slug': self.slug
            }
        ) 
    
    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Products, self).save(*args, **kwargs)

products/forms.py
from django import forms
from .models import Category, SubCategory, Products


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = '__all__'
        labels = {
            'name': 'Имя',
            'description': 'Описание',
            'slug': 'Url-адрес',
        }


class SubCategoryForm(forms.ModelForm):
    
    class Meta:
        model = SubCategory
        fields = '__all__'
        labels = {
            'name': 'Подкатегория',
            'category': 'Категория',
        }


class ProductForm(forms.ModelForm):
    # category = forms.ModelChoiceField(queryset=Category.objects.all())
    # subcategory = forms.ModelChoiceField(queryset=SubCategory.objects.all())
    class Meta:
        model = Products
        exclude = ['created_at', 'is_available']

products/views.py
from typing import Any, Dict
from django.forms.models import BaseModelForm
from django.shortcuts import get_object_or_404, render
from django.http import HttpRequest, HttpResponse
from django.views.generic import CreateView, ListView, DetailView
from .models import Category, SubCategory, Products
from .forms import CategoryForm, SubCategoryForm, ProductForm
from django.urls import reverse_lazy
from django import template

register = template.Library()


def index(request):
    category = Category.objects.all()
    context = {
        'category_list': category
    }

    return render(request, 'products/index.html', context=context)
   

class CategoryCreateView(CreateView):
    model = Category
    fields = '__all__'
    form = CategoryForm
    template_name = 'products/category-form.html'
    success_url = reverse_lazy('products:category-list')


class CategoryListView(ListView):
    model = Category
    template_name = 'products/category-list.html'
    context_object_name = 'categories'

   

class SubCategoryCreateView(CreateView):
    model = SubCategory
    fields = '__all__'
    form = SubCategoryForm
    template_name = 'products/subcategory-form.html'
    success_url = reverse_lazy('products:category-list')



def CategoryDetail(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    subcategory = SubCategory.objects.filter(category=category)
    context = {
        'category': category,
        'subcategory': subcategory
    }

    return render(request, 'products/category-detail.html', context=context)



class ProductCreateView(CreateView):
    model = Products
    fields = '__all__'
    form = ProductForm
    template_name = 'products/product-form.html'
    success_url = reverse_lazy('products:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['subcategories'] = SubCategory.objects.all()
        return context

    def form_valid(self, form):
        self.instance = form.save(commit=False)
        self.instance.category_id = self.request.POST.get('category')
        self.instance.subcategory_id = self.request.POST.get('subcategory')
        self.instance.save()
        return super().form_valid(form)


class ProductListView(ListView):
    model = Products
    template_name = 'products/product-list.html'
    context_object_name = 'products'


    def get_queryset(self):
        super().get_queryset()
        slug = self.request.resolver_match.kwargs['subcat_slug']
        queryset = Products.objects.filter(subcategory__slug = slug)
        return queryset
    
def get_category(self):
    category = Category.objects.all()
    context = {
        'category-list': category
    }
    return context

def add_to_cart(request, product_slug):
    return HttpResponse(product_slug)
       


class ProductDetailView(DetailView):
    model = Products
    template_name = 'products/product-detail.html'
    context_object_name = 'product'
    slug_url_kwarg = 'prod_slug'

products/templates/products/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>block title</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/menu.css'%}" type="text/css">
  <link rel="stylesheet" href="{% static 'css/product-card.css'%}" type="text/css">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  
</head>
<body>
  <style>
    body {
      background-image: url("{% static 'img/background.jpg' %}");
      background-repeat: no-repeat;
      background-size: cover;
    }  
  </style>
  <div class="menu-main">
    <div class="menu-item"><a href="{% url 'products:index' %}">Главная</a></div>
    <div class="menu-item"><a href="">Категории</a></div>
    {% if user.is_authenticated %}
    <div class="menu-item"><a href={% url "orders:order-list" %}>Заказы</a></div>
    {% endif %}
    <div class="menu-item"><a href="{% url 'cart:cart-detail' %}">Корзина</a></div>
    <div class="item-space"></div>
    {% if not user.is_authenticated %}
      <div class="menu-item"><a href="{% url 'users:register' %}">Зарегистрироваться</a></div>
      <div class="menu-item"><a href="{% url 'users:login' %}">Войти</a></div>
    {% endif %}
    {% if user.is_authenticated %}
      <div><a href="{% url 'users:logout' %}">Выйти</a></div>
    {% endif %}
</div>
  
    {% if user.is_authenticated %}
    <a style="margin-left:16px" href="{% url 'users:user-info' user.pk %}">{{user.username}}</a>
    {% endif %}

    <div class="cart">
      {% with total_items=cart|length %}
      {% if total_items > 0 %}
      <p class="text-right">
      Корзина:
      <a style="margin-right:30px" href="{% url "cart:cart-detail"%}">
        {{ total_items }} ед. -
        {{ cart.get_total_price }} руб.
      </a>
      {% else %}
      <p style="margin-right:30px" class="text-right">
      Корзина пуста.
      {% endif %}
      {% endwith %}
    </p>
    </div>

    {% for c in category_list  %}
    <li class="nav-item dropdown">
      <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <strong>{{ c.name }}</strong>
      </a>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        {% for subcategory in c.categories.all %}
        <a class="dropdown-item" href="{{ subcategory.get_absolute_url }}">{{ subcategory.name }}</a>
        {% endfor %}
      </div>
    </li>
    {% endfor %}

{% block content %}

{% endblock content %}    


</body>
</html>

products/templates/products/category-detail.html
<p>{{category.name}}</p>
<ul>
{% for subcat in subcategory %}
    <li>{{subcat.name}} {{subcat.slug}}</li>
{%endfor%}
</ul>

products/templates/products/category-form.html
<form action="{% url 'products:category-form' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Добавить категорию</button>
</form>

products/templates/products/category-list.html
{% extends 'products/base.html' %}
{% block content %}
<ul>
    {% for cat in categories %}
        <li> {{cat.name}} </li>
    <ul>
        {% for subcategory in cat.categories.all %}
            <li>{{ subcategory.name}}</li>
            
        {% endfor %}
    </ul>
    <br>
    {% endfor %}
  
</ul>



{% endblock %}

products/templates/products/index.html
{% extends 'products/base.html' %}

{% block content %}

{% endblock  %}

products/templates/products/product-detail.html
{% extends 'products/base.html' %}
{% load static %}
{% block content %}
{% load thumbnail %}

<div class="product-detail">
    {% if product.image %}
          {% thumbnail product.image "300" as im %}
            <a href="{{ product.get_absolute_url }}"><img src="{{im.url}}"></a>
          {% endthumbnail %}
        {% else %}
          <a href="{{ product.get_absolute_url }}"><img src="/static/img/no-image.png"></a>
      {% endif %}
      <h1>{{ product.name }}</h1>
      <h2>
        <a href="{{ product.category.get_absolute_url }}">
            {{ product.category }}
        </a>
    </h2>
  <p class="Price">{{ product.price }} руб. </p>
  {{ product.description|linebreaks}}
  <h2>
    <form action="{% url 'cart:cart-add' product.id %}" method='post'>
        {% csrf_token %}
        <input type="submit" value="В корзину">
    </form>
  </h2>
</div>


{% endblock %}

products/templates/products/product-form.html
{% load static %}
<form action="{% url 'products:product-form' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <label for="category">Категория:</label>
<select id="category" name="category">
  {% for category in categories %}
  <option value="{{ category.id }}">{{ category.name }}</option>
  {% endfor %}
</select>
 
<label for="subcategory">Подкатегория:</label>
<select id="subcategory" name="subcategory">
</select>
   <br>
   <button type="submit">Добавить товар</button>
</form> 


<script>
  var categories = {
      {% for category in categories %}
      "{{ category.id }}": {
        subcategories: [
          {% for subcategory in category.categories.all %}
          {
            id:"{{ subcategory.id }}",
            name:"{{ subcategory.name }}",
          },
          
          {% endfor %}
        ]
      },
      {% endfor %}
    };
  </script>
  <script src="{% static 'js/script.js' %}" type="text/javascript"></script>

products/templates/products/product-list.html
{% extends 'products/base.html' %}
{% load static %}
{% block content %}
{% load thumbnail %}

<link rel="stylesheet" href="{% static 'css/products.css'%}" type="text/css">

<div class="products">
    {% for prod in products %}
      <div class="product">
        {% if prod.image %}
          {% thumbnail prod.image "300" as im %}
            <a href="{{ prod.get_absolute_url }}"><img src="{{im.url}}"></a>
          {% endthumbnail %}
        {% else %}
          <a href="{{ prod.get_absolute_url }}"><img src="/static/img/no-image.png"></a>
      {% endif %}
          
        <h2>{{ prod.name }}</h2>
        <p>{{ prod.description }}</p>
        <p>{{ prod.price }} руб.</p>
        <p>
          <form action="{% url 'cart:cart-add' prod.id %}" method="post">
            {{ cart_product_form }}
            {% csrf_token %}
            <input type="submit" value="В корзину"> 
          </form>
        </p>
      </div>
    {% endfor %}
    </div>
    {% endblock %}

products/templates/products/subcategory-form.html
<form action="{% url 'products:subcategory-form' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить подкатегорию</button>
</form>